version: 1.3.{build}
image: Visual Studio 2022
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget.exe restore ProteinFileReader.sln
build:
  project: ProteinFileReader.sln
  verbosity: minimal
artifacts:
- path: bin\Release\net40\ProteinFileReader.dll
- path: bin\Release\ProteinFileReader*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: n9oXSkH88J7JrYQelJg/lIvcl1nIzRdPL3yAG3z3SJGSz6P8t9C1ehKXjiRsilLl
  skip_symbols: true
